FROM ubuntu:jammy-20221003

RUN apt-get update && apt-get upgrade -y && \
    # Install required libs
    apt-get install -y ca-certificates procps curl vim xz-utils git wget \
    bison flex make bc build-essential libncurses-dev libssl-dev libelf-dev liblz4-tool \
    python-is-python3 && \
    # get the gcc  \
    wget https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz --directory /home/tinkeros/ &&\
    # Setup gcc
    tar -xvf /home/tinkeros/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz --directory /home/tinkeros/ &&\
    rm /home/tinkeros/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz &&\
    git clone https://github.com/TinkerBoard2/kernel.git /home/tinkeros/kernel/ --progress

# adding gcc to path
ENV PATH="${PATH}:/home/tinkeros/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin"

########### References ###########
# https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/aarch64-linux-gnu/
# Note: https://tinker-board.asus.com/forum/index.php?/topic/14988-kernel-build-error-lz4c/